---
title: "HW4"
output: html_document
date: "2025-02-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1. Assigning each expression to the value of the variable z and print the value stored in z

```{r, eval=TRUE,echo=TRUE}
x <-1.1
a <- 2.2
b <- 3.3

# a 
z <-x^(a^b) 
print(z)

#b
z<- (x^a)^b
print(z) 

#c
z<-(3*x^3)+(2*x^2)+1
print(z)
```

#### 2.Using the rep and seq functions, create the following vectors

```{r, eval=TRUE,echo=TRUE}
my_vectorA <- c(seq(1, 8, by = 1), seq(7, 1, by = -1))
print(my_vectorA)

my_vectorB<- rep(1:5, 1:5)
print(my_vectorB)

my_vectorC<- rep(5:1, 5:1)
print(my_vectorC)
```

#### 3.Polar coordinates

```{r, eval=TRUE,echo=TRUE}
set.seed(1)
coor <- runif(2) #Creating a vector of two random uniform numbers
print(coor)
x <- coor[1]
print(x)
y <- coor[2]
print(y)

#calculating the radius 
radius <- sqrt(x^2 + y^2)
print(radius)

#calculating the theta with atan() function
theta <- atan(y / x)
print(theta)

```

#### 4.Noah’s Ark

```{r, eval=TRUE,echo=TRUE}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
#the serpent arrives and gets in line
queue<-c(queue,"serpent") 
print(queue)
#the sheep enters the ark
queue <- queue[-which(queue == "sheep")]
print(queue)
#the donkey arrives and talks his way to the front of the line
queue<-c("donkey", queue)
print(queue)
#the serpent gets impatient and leaves
queue <- queue[-which(queue == "serpent")]
print(queue)
#the owl gets bored and leaves
queue <- queue[-which(queue == "owl")]
print(queue)
#the aphid arrives and the ant invites him to cut in line.
which(queue == "ant")
queue <- c(queue[1:(3-1)], "aphid", queue[3:length(queue)])
print(queue)
#Finally, determine the position of the aphid in the line.
which(queue == "aphid")
```

#### 5.Using arithmetic operators to filter a vector to get a sequence from 1 to 100 with numbers not divisibles by 2, 3, or 7

```{r, eval=TRUE,echo=TRUE}
X <-1:100
Xfiltered <- X[!(X %% 2 == 0 | X %% 3 == 0 | X %% 7 == 0)]
print(Xfiltered)
```
